apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-appsettings-secrets
type: Opaque
data:
  appsettings.{{ .Values.aspNetEnvironment }}.json: {{- toJson .Values.secretData | b64enc | indent 2}}

