# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

on:
  push:
    branches:
    - main
    - release/*

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
      uses: docker/build-push-action@v5.3.0
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: ./services
        # Path to the Dockerfile
        file: ./services/IdentityServer.Admin.Dockerfile
        tags: latest
