# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: docker_build_ids_admin

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

on:
  workflow_dispatch: 
  push:
    branches:
      - release/*
    tags:
      - "v*.*.*"

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set environment
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}_${GITHUB_SHA}" | tr / _ | tr . _ >> $GITHUB_ENV
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            doitsu2014/doitsu-technology-ids-admin
            registry.hub.docker.com/doitsu2014/doitsu-technology-ids-admin
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          flavor: |
            latest=auto
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          # Build's context is the set of files located in the specified PATH or URL
          context: "./services/"
          # Path to the Dockerfile
          file: "./services/IdentityServer.Admin.Dockerfile"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}